### ISSUE TITLE
Add further indices

### ISSUE THREAD

**Issue by MarcoLandtHayen** [MarcoLandtHayen/climate_index_collection#22]
- [x] Add North Atlantic Oscillation (NAO) index station-based (https://climatedataguide.ucar.edu/climate-data/hurrell-north-atlantic-oscillation-nao-index-station-based).
- [x] Add Southern Annular Mode (SAM) index from zonal mean (https://climatedataguide.ucar.edu/climate-data/marshall-southern-annular-mode-sam-index-station-based). (See #7)
- [x] Add ENSO from Nino3.4 box area-averaged (https://climatedataguide.ucar.edu/climate-data/nino-sst-indices-nino-12-3-34-4-oni-and-tni). (See #39)
- [x] #63
- [x] #57
- [x] #79
- [x] #113
- [x] #97
- [x] Sea Air Surface Temperature Anomaly index (SATAI) for Northern / Southern hemisphere and globally (https://www.ncei.noaa.gov/access/monitoring/global-temperature-anomalies/anomalies), need SATA data first (see #47) also (see #67).
- [x] Sea Surface Salinity Anomaly index (#68)
- [x] #110
- [x] #112

See https://oceanrep.geomar.de/id/eprint/54927/ (pages 5ff) for full set of desired indices, at least in the first step.

**Comment by MarcoLandtHayen** [comment]
For now, the collection is complete. Might add additional indices later.
